- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

- name: MongoDB | Install ppa
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present

- name: MongoDB | Install package
  apt: name=mongodb-org state=present force=yes
  notify: restart mongod
  register: mongoapt

- name: Validate Backup parameter
  fail: msg="mongo_backup_location is not passed or blank"
  when: "backup_mongo and mongo_backup_location is not defined or ( mongo_backup_location is defined and mongo_backup_location == '' )"

- name: MongoDB | Backup {{ mongo_db }}
  command: mongodump --host {{ mongo_uri }} --db {{ mongo_db }} --out {{ mongo_backup_location }}
  when: "backup_mongo and not mongoapt.changed"
  sudo: yes

- name: Pack backup
  command: tar -czf {{ mongo_db }}.tar.gz {{ mongo_db }}
  args:
    chdir: "{{ mongo_backup_location }}"
  when: "backup_mongo and not mongoapt.changed"

- name: MongoDB | Download {{ mongo_db }} Backup
  fetch: "src={{ mongo_backup_location }}{{ mongo_db }}.tar.gz dest={{ mongo_backup_location_local }}{{ mongo_db }}{{ mongo_backup_location_local_append }}.tar.gz flat=yes fail_on_missing=yes"
  when: "backup_mongo and download_backup_mongo and not mongoapt.changed"
  sudo: yes

- name: MongoDB | Copy and Unpack Backup
  unarchive: src={{ mongo_backup_location_local }}{{ mongo_db }}{{ mongo_backup_location_local_append }}.tar.gz dest={{ mongo_backup_location }} copy=yes
  when: "restore_mongo and use_local_backup_during_restore and not mongoapt.changed"

- name: Check Backup Directory
  stat: path={{ mongo_backup_location }}{{ mongo_db }}
  register: backup_folder_stat

- name: Validate Backup Directory
  fail: msg="Backup directory {{ mongo_backup_location }}{{ mongo_db }} does not exist"
  when: "backup_folder_stat.stat.isdir is not defined and not mongoapt.changed"

- name: MongoDB | Restore {{ mongo_db }}
  command: mongorestore --host {{ mongo_uri }} --db {{ mongo_db }} --drop {{ mongo_backup_location }}{{ mongo_db }}
  args:
    chdir: "{{ mongo_backup_location }}{{ mongo_db }}"
  when: "restore_mongo and not mongoapt.changed"